fn main() {
    let is_windows = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows");
    let attributes = if is_windows {
        // The manifest is linked below for every executable target, including Cargo's
        // unit-test harness. Keep it out of the binary-only resource generated by
        // `tauri-build` so the application binary does not receive it twice.
        tauri_build::Attributes::new()
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest())
    } else {
        tauri_build::Attributes::new()
    };
    tauri_build::try_build(attributes).expect("failed to run Tauri build script");

    if is_windows {
        let manifest = std::path::Path::new("windows-app-manifest.xml")
            .canonicalize()
            .expect("Windows application manifest must exist");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
    }
}
